[package]
name = "piercast-schema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Serde types for Piercast app configuration"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
